---
kind: pipeline
name: splatnet2statink-master

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: titouanco/splatnet2statink
    tags: latest
    username:
      from_secret: docker_username

...
